### PR TITLE
moubarek-barre-hassan-Hw1

### PR DESCRIPTION
**Pull request by MOUBAREK1998**

### CODE REVIEW

**Review by NataRazmochaeva — CHANGES_REQUESTED** [review]
1. Task1 -- fix compilation errors:
image

2. Task 2 -- the same, fix errors:
image

**Comment by NataRazmochaeva** [comment]
task1.c -- correct

**Comment by NataRazmochaeva** [comment]
task3 -- correct

**Comment by MOUBAREK1998** [comment]
Please Task2.c  isn't correct? or what about task2.c?

**Comment by MOUBAREK1998** [comment]
Please how about task2.c?

**Comment by MOUBAREK1998** [comment]
I saw my mark now.
thank you

**Pull request merged**
